#!/usr/bin/env ruby

remotes = `git remote -v`.split(/\n/).each_with_object({}) do |line, obj|
  name, url, _ = line.split(/\s+/)
  obj[name] = url
end

remotes.each do |name, url|
  if url =~ /github\.com/ && url =~ /manualdesign/
    new_url = url.gsub(/manualdesign/, "kord-as")
    puts "Updating #{name} (#{url} -> #{new_url})"
    `git remote set-url origin #{new_url}`
  end
end
